YeniTakip/Controllers/DepoKontrolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YeniTakip.HelpDesk;
using YeniTakip.Models;
namespace YeniTakip.Controllers
{
    public class DepoKontrolController : Controller
    {
        // GET: DepoKontrol
        public ActionResult Kontrol()
        {
            Helper h = new Helper();
            
            STEmreDBEntities3 db = new STEmreDBEntities3();

            List<Depolar> depos = db.Depolar.ToList();
            List<DepoDetaylari> depodetay = new List<DepoDetaylari>();
            List<Raflar> rafs = db.Raflar.ToList();
            List<RafDetaylari> rafdetay = new List<RafDetaylari>();

            foreach (var item in depos)
            {
                DepoDetaylari dpdt = new DepoDetaylari();
                dpdt.DepoAdi = item.DepoAdi;
                dpdt.ToplamAlan= h.DepoAlanGetir(item.DepoID) ?? 0;
                dpdt.KapladigiAlan = h.KapladigiAlan(item.DepoID) ?? 0;
                dpdt.KalanAlan = dpdt.ToplamAlan - dpdt.KapladigiAlan;
                depodetay.Add(dpdt);
            }

            ViewBag.depodetaylari = depodetay;

            
            //using (db)
            //{
            //    List<RafDetaylari> rafbilgiler = db.Database.SqlQuery<RafDetaylari>(
            //           "SELECT DepoID, KapladigiAlan, Count(KapladigiAlan) as Adeti FROM Raflar GROUP BY KapladigiAlan,DepoID").ToList();

            //ViewBag.rafcantam = rafbilgiler;
            //}



            foreach (var rafitem in rafs)
            {
                RafDetaylari rfdt = new RafDetaylari();
                rfdt.DepoAdi = rafitem.Depolar.DepoAdi;
                rfdt.Raftoplamalan = h.RafAlan(rafitem.RafID) ?? 0;
                rfdt.Rafkaplananalan = h.UrunBoyut(rafitem.RafID) ?? 0;
                rfdt.Rafkalanalan = (rfdt.Raftoplamalan - rfdt.Rafkaplananalan);
                rafdetay.Add(rfdt);
            }

            ViewBag.rafdetaylari = rafdetay;





            return View();
        }
    }
}

YeniTakip/Controllers/GirdiCiktiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YeniTakip.HelpDesk;
using YeniTakip.Models;

namespace YeniTakip.Controllers
{
    public class GirdiCiktiController : Controller
    {
        // GET: GirdiCikti
        static string mesaj = "";
        static string mesaj2 = "";
        static string mesaj3 = "";
        public ActionResult UrunEklemeCikarma()
        {   
            STEmreDBEntities3 db = new STEmreDBEntities3();
            //List<Kullanici> kullanicilar = db.Kullanici.ToList();
            //ViewBag.kullanicibilgileri = kullanicilar;

            //List<HareketTur> adlar = db.HareketTur.ToList();
            //ViewBag.hareketbilgileri = adlar;

            //List<Depolar> depoid = db.Depolar.ToList();
            //ViewBag.depoidleri = depoid;

            //List<Tedarikci> tedarikciler = db.Tedarikci.ToList();
            //ViewBag.tedarikcibilgileri = tedarikciler;

            // List<Raflar> rafIdler = db.Raflar.ToList();
            //ViewBag.rafbilgileri = rafIdler;


            //var urunkodu = new List<Urunler>();

            

            //ViewBag.durum = mesaj;
            //ViewBag.durum2 = mesaj2;
            //ViewBag.durum3 = mesaj3;

            return View();
        }

        //[HttpPost]
        //public ActionResult Kaydet()
        //{
            //STEmreDBEntities3 db = new STEmreDBEntities3();
            //UrunHareket urunhareket = new UrunHareket();
            //Urunler urun = db.Urunler.Where(x => x.UrunKodu == ud.UrunKodu).FirstOrDefault();
            //List<GetUrunMevcutListe_Result> mevcut = db.GetUrunMevcutListe(ud.UrunKodu, ud.DepoID).ToList();
            //Helper h = new Helper();
            //if (urun != null)
            //{
            //    if (ud.HareketTurID == 36)
            //    {
            //        mesaj3 = h.GirisKontrol(ud);
            //    }
            //    else if(ud.HareketTurID == 35)
            //    {
            //        mesaj3 = h.CikisKontrol(ud);
            //    }
            //}
            //else
            //{
            //    mesaj = "Ürün Kaydı Bulunamadı !";
            //}

            //ViewBag.urunss = urun;

            //return RedirectToAction("UrunEklemeCikarma");
        //}

        /*[HttpPost]
        public JsonResult UrunGetir()
        {
            //STEmreDBEntities3 db = new STEmreDBEntities3();
            //db.Configuration.LazyLoadingEnabled = false;
            //Urunler urun = db.Urunler.Where(x => x.UrunKodu == UrunKod).FirstOrDefault();
            //if(urun == null)
            //{
            //    urun = new Urunler();
            }
            return Json();
        }*/
    }
}

YeniTakip/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace YeniTakip.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

YeniTakip/Controllers/IslemRaporuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YeniTakip.Models;
namespace YeniTakip.Controllers
{
    public class IslemRaporuController : Controller
    {
        public ActionResult Rapor()
        {
            Islemler islems = new Islemler();
            STEmreDBEntities3 db = new STEmreDBEntities3();
            List<Depolar> depoids = db.Depolar.ToList();
            ViewBag.depoidleri = depoids;
            return View(islems);

        }

        // GET: İslemRaporu
        [HttpPost]
        public ActionResult Rapor(Islemler islems)
        {
        //    DateTime time = new DateTime(1, 1, 1, 0, 0, 0, DateTimeKind.Utc);
        //    if (islems.BaslangicTarihi == time)
        //    {
        //        islems.BaslangicTarihi = null;
        //    }

            STEmreDBEntities3 db = new STEmreDBEntities3();

            var urunler = new List<GetIslemRaporu_Result>();

            if (!String.IsNullOrEmpty(islems.UrunKodu))
            {
                urunler = db.GetIslemRaporu(islems.DepoID, islems.UrunKodu, islems.BaslangicTarihi, islems.BitisTarihi).ToList<GetIslemRaporu_Result>();
            }
            ViewBag.sonuc = urunler;
          
            List<Depolar> depoids = db.Depolar.ToList();
            ViewBag.depoidleri = depoids;
            return View(new Islemler());

        }
    }
}

YeniTakip/Controllers/UrunSorgulamaController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace YeniTakip.Controllers
{
    public class UrunSorgulamaController : Controller
    {
        // GET: UrunSorgulama
        public ActionResult Sorgula()

        {
            STEmreDBEntities3 db = new STEmreDBEntities3();            
            List<Depolar> adlar = db.Depolar.ToList();
            ViewBag.cantam = adlar;
            return View(new List<GetUrunMevcutListe_Result>());
        }
        [HttpPost]
        public ActionResult Sorgula(string searching)
        {
            STEmreDBEntities3 db = new STEmreDBEntities3();

            var urunler = new List<GetUrunMevcutListe_Result>();
            var depoid = new List<Depolar>();

            if (!String.IsNullOrEmpty(searching))
            {
                urunler = db.GetUrunMevcutListe(searching,null).ToList<GetUrunMevcutListe_Result>();
            }
            List<Depolar> adlar = db.Depolar.ToList();
            ViewBag.cantam = adlar;
            return View(urunler);
        }
        [HttpPost]
        public ActionResult DepoyaGoreSorgula(string depo)
        {
            STEmreDBEntities3 db = new STEmreDBEntities3();
            int? arama = Convert.ToInt32(depo);
            var uruns = new List<GetUrunMevcutListe_Result>();
            uruns = db.GetUrunMevcutListe(null, arama).ToList<GetUrunMevcutListe_Result>();
            ViewBag.canta = uruns;
            List<Depolar> adlar = db.Depolar.ToList();
            ViewBag.cantam = adlar;
            return View("Sorgula");
        }
      
    }
}

YeniTakip/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div class="col-12">
    <div class="row">
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-primary o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fas fa-fw fa-comments"></i>
                    </div>
                    <a href="@Url.Action("UrunEklemeCikarma","GirdiCikti")" class="card-footer text-white clearfix small z-1">
                        <h4 class="float-left">Ürün Girdi-Çıktı</h4>
                        <span class="float-right">
                            <i class="fas fa-angle-right"></i>
                        </span>
                    </a>
                    @*<div class="mr-5">26 New Messages!</div>*@
                </div>

            </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-warning o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fas fa-fw fa-list"></i>
                    </div>
                    <a href="@Url.Action("Sorgula", "UrunSorgulama")" class="card-footer text-white clearfix small z-1">
                        <h4 class="float-left">Ürün Sorgulama</h4>
                        <span class="float-right">
                            <i class="fas fa-angle-right"></i>
                        </span>
                    </a>
                    @*<div class="mr-5">11 New Tasks!</div>*@
                </div>

            </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-success o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fas fa-fw fa-shopping-cart"></i>
                    </div>
                    <a href="@Url.Action("Kontrol", "DepoKontrol")" class="card-footer text-white clearfix small z-1" >
                        <h4 class="float-left">Depoları Kontrol Et</h4>
                        <span class="float-right">
                            <i class="fas fa-angle-right"></i>
                        </span>
                    </a>
                    @*<div class="mr-5">123 New Orders!</div>*@
                </div>

            </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-danger o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fas fa-fw fa-life-ring"></i>
                    </div>
                    <a href="@Url.Action("Rapor", "IslemRaporu")" class="card-footer text-white clearfix small z-1">
                        <h4 class="float-left">İşlem Raporu Al</h4>
                        <span class="float-right">
                            <i class="fas fa-angle-right"></i>
                        </span>
                    </a>
                    @*<div class="mr-5">13 New Tickets!</div>*@
                </div>

            </div>
        </div>
    </div>
</div>